# Generated by Django 2.2.5 on 2019-09-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_um', models.CharField(max_length=120)),
                ('referencia_dois', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
